### ISSUE TITLE
Version Calculation for Snapshot Versions

### ISSUE THREAD

**Issue by simpleprovider** [trygvis/unix-maven-plugin#8]
Hi,

I have a problem regarding the versions  with the your latest  plugin.
When I call "mvn deploy" the version generated by maven will differ from version generated by the plugin and added in pkg/rpm info .

The difference is about 2 seconds. 

Example :
For pom with version 1.0-Snapshot
Pkg/Rpm version will be : 1.0-20121030.102100  
Maven metadata version , used as well for the name of the file will be:     1.0-20121030.102102
Aren't they supposed to be the same like before ?

Were there any changes to the  way these versions are generated, this problem didn't occur with previous maven-unix-plugin.

Thanks,

**Comment by trygvis** [comment]
That is a known "feature" after Maven broke its API from Maven 2 to Maven 3. I haven't been able to find a good workaround for the problem yet. If you really need consistent timestamps (I know they're very useful) you'll have to use Maven 2 and the older versions of the plugins. Sorry.

## 

Trygve

**Comment by simpleprovider** [comment]
So Maven changed their API.
Good to know what is creating the issue. 
Thank you for your quick reply.

Regards,
Adrian
