### ISSUE TITLE
Output artifacts naming

### ISSUE THREAD

**Issue by nikelin** [trygvis/unix-maven-plugin#9]
Is there any possible way to change current behavior of naming scheme for resulted _.deb/_.rpm packages?

In my case I have two profiles (_development_ and _production_) of a single module which help to decide which dependency to include in final *.deb package, so I need a some ability to distinguish between them.

But, all documented possibilities does not works for me (<outputFile/>, <finalName/> - ingored) and there is no option like <classifier> I had found for the plugin <configuration/>.

So, for a now I have only two choices: 1) To split current module configuration into 2 separated modules for each profile needs to be built; 2) To use variable part in <artifactId/> which will lead to situation which same to p. 1. which inappropriate for me. 

Can you, please, make me advice about where and how I can add such behavior into the plugin logic or otherwise how this can be solved?

Thank you!

**Comment by trygvis** [comment]
On Mon, Jan 21, 2013 at 02:27:18AM -0800, Cyril A. Karpenko wrote:

> Is there any possible way to change current behavior of naming scheme for resulted _.deb/_.rpm packages?

No, not really. It follows the Maven convention wrt naming.

> In my case I have two profiles (_development_ and _production_) of a single module which help to decide which dependency to include in final *.deb package, so I need a some ability to distinguish between them.
> 
> But, all documented possibilities does not works for me (<outputFile/>, <finalName/> - ingored) and there is no option like <classifier> I had found for the plugin <configuration/>.

You can use the <classifier> inside <package> if you really want to create packages.

Here is an example: https://svn.codehaus.org/mojo/trunk/mojo/unix/unix-maven-plugin/src/it/test-sysvpkg-3/pom4test.xml

> So, for a now I have only two choices: 1) To split current module configuration into 2 separated modules for each profile needs to be built; 2) To use variable part in <artifactId/> which will lead to situation which same to p. 1. which inappropriate for me. 
> 
> Can you, please, make me advice about where and how I can add such behavior into the plugin logic or otherwise how this can be solved?

A third option is to not build separate packages, but have a
postinstall script in the package determine which configuration it
should use.

All my experience with building environment-specific packages results
in total, gigantic clusterfucks. It becomes extremely complex very,
very soon. Just don't do it. It's hell. I've been there.

## 

Trygve

**Comment by nikelin** [comment]
Packages that is exactly what I wanted. Thank you very much for your helpful advice!
